# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - antitwinklinkstack

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
   group: Build and deploy PHP app to Azure Web App - antitwinklinkstack
   cancel-in-progress: true

permissions: write-all

jobs:
  build:
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Remove .git & .github directories
        shell: bash
        run: rm -rf .git .github

      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r

        # You may pin to the exact commit or the version.
        # uses: LanceMcCarthy/Action-AzureBlobUpload@36804997c22518c2f7d0a508d6ff5593d4b4722e
      - name: Uplodad NGINX configuration
        uses: LanceMcCarthy/Action-AzureBlobUpload@v3.1.3
        with:
          # Azure Storage ConnectionString for the container (Azure Portal - select Storage Account - Access Keys blade).
          connection_string: ${{ secrets.AZURE_BLOBS_CONNECTION_STRING }}
          # Blob Container name (e.g. my-container).
          container_name: etcnginx
          # The local folder containing all the files and subfolders to upload to the blob container (use a trailing slash).
          source_folder: ./nginx
          # The target folder to use in the blob container with (do not use a leading or trailing slash).
          # destination_folder: # optional
          # This option will delete all the blobs in destination_folder before uploading the new files.
          clean_destination_folder: true
          # If you want the Action to fail and report an error if the source_folder is empty.
          fail_if_source_empty: true # optional
          # Set to false if you want all subfolders ignored.
          is_recursive: true # optional, default is true
          # If the blob exists it will be skipped, unless this is set to true.
          delete_if_exists: true # optional
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'antitwinklinkstack'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5093A740C8CE4D53B0CD91B7B5F8462C }}
          target-path: /home/site/wwwroot/public
          # restart: true
          # clean: true
          # type: ZIP
