# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - antitwinklinkstack

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
   group: Build and deploy PHP app to Azure Web App - antitwinklinkstack
   cancel-in-progress: true

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Remove .git & .github directories
        shell: bash
        run: rm -rf .git .github

      - name: Move everything to the /public directory
        shell: pwsh
        run: |
          # Define the source folder
          $sourceFolder =  $(Get-location)
          
          # Define the destination subfolder
          $destinationSubfolder = "$(Get-location)/public"
          
          # Create the destination subfolder if it doesn't exist
          if (-Not (Test-Path -Path $destinationSubfolder)) {
              New-Item -ItemType Directory -Path $destinationSubfolder
          }
          
          # Move all items from the source folder to the destination subfolder
          Get-ChildItem -Path $sourceFolder | ForEach-Object {
              if ($_.FullName -ne $destinationSubfolder) {
                  Move-Item -Path $_.FullName -Destination $destinationSubfolder
              }
          }

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BFE005C5E3B0449EBA384DB426E31BFF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_84E6C32B44FB45BEA433E8E42A72ABC7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B114AC5D505C4881B6DFD3E8E9E09223 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'antitwinklinkstack'
          slot-name: 'Production'
          package: .
          
  clean-up:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Clean up build artifacts
      uses: dgmjr-actions/cleanup-build-artifacts@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
